### ISSUE TITLE
Error using schemas with MSSQL

### ISSUE THREAD

**Issue by leogouveia** [rmp135/sql-ts#129]
When I try to use the 'schemas' option in the configuration object, I receive the error below which I believe to be a query error written by Knex.
Here is my config object:

```javascript
const config = {
  client: "mssql",
  connection: {
    host: "localhost",
    user: "",
    password: "",
  },
  schemas: ["test"],
};
```

And here is the error:

```javascript
/home/leogouveia/Dev/repos/sql-ts/node_modules/tedious/lib/request.js:306
        throw new _errors.RequestError('Validation failed for parameter \'' + parameter.name + '\'. ' + error.message, 'EPARAM');
              ^

RequestError: 
      SELECT
        TABLE_NAME name,
        TABLE_SCHEMA [schema],
        COALESCE(EP.value, '') comment
        FROM INFORMATION_SCHEMA.TABLES
        OUTER APPLY (
          SELECT TOP 1 value FROM fn_listextendedproperty (NULL, 'schema', TABLE_SCHEMA, 'table', TABLE_NAME, null, null) EP WHERE EP.name = 'MS_Description'
          UNION
          SELECT TOP 1 value FROM fn_listextendedproperty (NULL, 'schema', TABLE_SCHEMA, 'view', TABLE_NAME, null, null) EP WHERE EP.name = 'MS_Description'
        ) EP 
      WHERE TABLE_SCHEMA IN (@p0) - Validation failed for parameter 'p0'. Invalid string.
    at Request.validateParameters (/home/leogouveia/Dev/repos/sql-ts/node_modules/tedious/lib/request.js:306:15)
    at Connection.execSql (/home/leogouveia/Dev/repos/sql-ts/node_modules/tedious/lib/connection.js:1748:15)
    at Client_MSSQL._chomp (/home/leogouveia/Dev/repos/sql-ts/node_modules/knex/lib/dialects/mssql/index.js:210:20)
    at Client_MSSQL._enqueueRequest (/home/leogouveia/Dev/repos/sql-ts/node_modules/knex/lib/dialects/mssql/index.js:217:10)
    at /home/leogouveia/Dev/repos/sql-ts/node_modules/knex/lib/dialects/mssql/index.js:405:12
    at new Promise (<anonymous>)
    at Client_MSSQL._query (/home/leogouveia/Dev/repos/sql-ts/node_modules/knex/lib/dialects/mssql/index.js:385:12)
    at executeQuery (/home/leogouveia/Dev/repos/sql-ts/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MSSQL.query (/home/leogouveia/Dev/repos/sql-ts/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/home/leogouveia/Dev/repos/sql-ts/node_modules/knex/lib/execution/runner.js:123:36) {
  code: 'EPARAM',
  number: undefined,
  state: undefined,
  class: undefined,
  serverName: undefined,
  procName: undefined,
  lineNumber: undefined
}

Node.js v18.15.0
```

I believe that this code in mssql is generating this error:

```javascript
async getAllTables(db: Knex, schemas: string[]): Promise<TableDefinition[]> {
    const sql = `
      SELECT
        TABLE_NAME name,
        TABLE_SCHEMA [schema],
        COALESCE(EP.value, '') comment
        FROM INFORMATION_SCHEMA.TABLES
        OUTER APPLY (
          SELECT TOP 1 value FROM fn_listextendedproperty (NULL, 'schema', TABLE_SCHEMA, 'table', TABLE_NAME, null, null) EP WHERE EP.name = 'MS_Description'
          UNION
          SELECT TOP 1 value FROM fn_listextendedproperty (NULL, 'schema', TABLE_SCHEMA, 'view', TABLE_NAME, null, null) EP WHERE EP.name = 'MS_Description'
        ) EP 
      ${schemas.length > 0 ? `WHERE TABLE_SCHEMA IN (:schemas)` : ''}`
    return await db.raw(sql, { schemas })
  }
```

That's what knex docs suggest to use with raw expression and IN filter:
https://knexjs.org/guide/raw.html
```javascript
const myArray = [1,2,3]
knex.raw('select * from users where id in (' + myArray.map(_ => '?').join(',') + ')', [...myArray]);

```

**Comment by rmp135** [comment]
This used to work in an older version of the mssql driver, they must have updated away from it. I've updated the adapter to support the expression as above.
