### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by ShahriarKh** [rmp135/sql-ts#141]
When I want to run the module, I get this error. Could it be related to Node version?
```bash
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Module.join (node:path:429:7)
    at Module.applyConfigDefaults (file:///**my-project-path**/node_modules/@rmp135/sql-ts/dist/ConfigTasks.js:25:24)
    at Client.fromConfig (file:///**my-project-path**/node_modules/@rmp135/sql-ts/dist/Client.js:16:37)
    at file:///**my-project-path**/generator.mjs:34:33
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.18.2
```

This is my `generator.mjs`

```js
import { Client } from '@rmp135/sql-ts';

const config = {
  client: 'mssql',
  connection: {
    host: 'localhost',
    user: 'myuser',
    password: 'mypass',
    database: 'mydb',
  },
};

const definition = await Client.fromConfig(config)
  .fetchDatabase()
  .toTypescript();
```

**Comment by ShahriarKh** [comment]
Yeah that was the problem. I upgraded node and now it works.
BTW, I created a pr to warn about it: #142

**Comment by hhanesand** [comment]
Perhaps we could support node 18 instead - #144 ? 😄

**Comment by rmp135** [comment]
Yea, the best outcome here is the increase the node version range. I've pushed version 2.1.0 and tested it with both 18 and 20 so hopefully it should work with both. 

Let me know if it fixes your issue.
